#!/usr/bin/env bash

if [ -n "${__bash_aux_included__}" ]; then return 0; fi
export __bash_aux_included__=true

if [ -z "${BASH_AUX_DIR}" ]; then
    current_file=
    if [ -n "$BASH_VERSION" ]; then
        current_file="${BASH_SOURCE[0]}"
    elif [ -n "$ZSH_VERSION" ]; then
        current_file="${(%):-%x}"
    fi
    BASH_AUX_DIR="$(dirname $(readlink -f "${current_file}"))"
fi

# ========================== > Source submodules < =========================== #
source ${BASH_AUX_DIR}/submodules/bash-doc/bash-doc-init
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ===================== > Source and export functions < ====================== #
source ${BASH_AUX_DIR}/functions/check_dependencies
source ${BASH_AUX_DIR}/functions/check_dependency
source ${BASH_AUX_DIR}/functions/current_file
source ${BASH_AUX_DIR}/functions/make_file_path
source ${BASH_AUX_DIR}/functions/normalize_path
source ${BASH_AUX_DIR}/functions/read_from_file
source ${BASH_AUX_DIR}/functions/read_non_blocking
# ────────────────────────────────── <end> ─────────────────────────────────── #
# ========================= > Export all functions < ========================= #
eval "$(declare -F |
    perl -p0e "s/declare\s+-f\s+(.*)\s*$/export -f \${1}/gmi" )"
# ────────────────────────────────── <end> ─────────────────────────────────── #
