---
title: bash-aux
output:
  github_document
---

```{r, echo=FALSE,include=FALSE}
# Make sure colors from tput are used correctly in the output
options(crayon.enabled = TRUE)
knitr::knit_hooks$set(output = function(x, options) {
  paste0(
  #   "<svg fill=\"none\" viewBox=\"0 0 600 300\" width=\"600\" height=\"300\" xmlns=\"http://www.w3.org/2000/svg\">",
  # "<foreignObject width=\"100%\" height=\"100%\">",
    '<pre class="r-output">',
    paste0(
      "<code>",
      paste0(
        fansi::to_html(
          x =
            htmltools::htmlEscape(x),
          warn = FALSE,
          carry = FALSE
        ),
        collapse = "  \n"
      ),
      "</code>",
      collapse = "\n"
    ),
    "</pre>"
    # "</foreignObject>",
# "</svg>"
  )
})
num_colors <- function(forget = TRUE) 256
library(crayon)
assignInNamespace("num_colors", num_colors, pos = "package:crayon")
Sys.setenv("TERM" = "dumb")

print_help <-
  function(x) {
    cat(
      system(
        paste0(
          "/usr/bin/env bash -c \"source ./bash-aux-init && ",
      x,
      " --help\""
      ), 
      intern = TRUE),
      sep =
        "\n"
    )
  }
```

Collection of helpful functions for [bash](https://www.gnu.org/software/bash/).
Core functions are outlined below.

# Core functions

## Dependency checks

### check_dependencies
```{r, eval=TRUE, echo=FALSE,include=TRUE,comment=""}
print_help("check_dependencies")
```

### check_dependency
```{r, eval=TRUE, echo=FALSE,include=TRUE,comment=""}
print_help("check_dependency")
```

## Folders & Files

### current_file
```{r, eval=TRUE, echo=FALSE,include=TRUE,comment=""}
print_help("current_file")
```

### make_file_path
```{r, eval=TRUE, echo=FALSE,include=TRUE,comment=""}
print_help("make_file_path")
```

### normalize_path
```{r, eval=TRUE, echo=FALSE,include=TRUE,comment=""}
print_help("normalize_path")
```

### read_from_file
```{r, eval=TRUE, echo=FALSE,include=TRUE,comment=""}
print_help("read_from_file")
```

## Logging

```{r, eval=TRUE, echo=FALSE,include=TRUE,comment=""}
print_help("bash_aux_log")
```

## Misc

### read_non_blocking
```{r, eval=TRUE, echo=FALSE,include=TRUE,comment=""}
print_help("read_non_blocking")
```
